<?php
$vmncats = "";
$vmnsecs = "";
$previewusers = "24";
$mailusers = "24";
$interval = "1";
$logsize = "25";
$useverificationemail = "1";
$vmsubject = "Verify your subscriptions";
$vmchosencat = "You have chosen to subscribe to the following categories:";
$vmnocats = "You have chosen to end all your subscriptions";
$vmlinktext = "Click here to update your subscriptions";
$verifymailHTML = "<html>
<head>
<title>[subject]</title>
</head>
<body>
<font face=\"Verdana, Arial, Helvetica, sans-serif\">
<table cellpadding=\"10\" width=\"100%\">
  <tr>
    <td>
      [subject] to news from [sitename]<br><br>
      <img src=\"[livesite]/administrator/components/com_vemod_news_mailer/vemod.jpg\">
    </td>
  </tr>
  <tr>
    <td width=\"100%\" valign=\"top\">
      <font size=\"-1\">
      <strong><font size=\"+1\">Hello [username]!</font></strong><br><br>
      [subscribeto]<br><br>
      [verifylink]
      </font>
    </td>
  </tr>
  <tr>
    <td>
      <font size=\"-2\"><strong>This is an autogenerated mail, please do not respond</strong></font>
    </td>
  </tr>
</table>
</font>
</body>
</html>";
$verifymailText = "[subject] to news from [sitename]

Hello [username]!

[subscribeto]

[verifylink]

This is an autogenerated mail, please do not respond";
$usereadmore = "1";
$readmoretext = "Read more...";
$readmoretruncate = "500";
$compiledreadmoretext = "Read more...";
$compiledreadmoretruncate = "150";
$sidebarmodule1 = "mod_latestnews";
$sidebarmodule2 = "mod_mostread";
$sidebarmodule3 = "";
$sidebarmodule4 = "";
$newsmailHTML = "<html>
<head>
<title>News from [sitename]</title>
</head>
<body>
<font face=\"Verdana, Arial, Helvetica, sans-serif\">
<table cellpadding=\"10\" width=\"100%\">
  <tr>
    <td>
      News from [sitename]<br><br>
      <img src=\"[livesite]/administrator/components/com_vemod_news_mailer/vemod.jpg\">
    </td>
    <td bgcolor=\"#EEEEEE\" valign=\"top\" rowspan=\"4\">
      <strong><font size=\"+1\">What\'s hot?</font></strong><hr>
      <strong>[moduletitle1]</strong><br>
      <font size=\"-1\">
      [modulecontent1]<hr>
      </font>
      <strong>[moduletitle2]</strong><br>
      <font size=\"-1\">
      [modulecontent2]
      </font>
    </td>
  </tr>
  <tr>
    <td width=\"80%\" valign=\"top\">
      <strong>[title]</strong><br><br>
      <font size=\"-1\">
      <em>[introtext]</em><br><br>
      [bodytext]
      </font>
    </td>
  </tr>
  <tr>
    <td>
      <font size=\"-1\">
      [unsubscribeall]
      </font>
    </td>
  </tr>
  <tr>
    <td>
      <font size=\"-2\">
      <strong>This is an autogenerated news mail, please do not respond</strong>
      </font>
    </td>
  </tr>
</table>
</font>
</body>
</html>";
$newsmailText = "News from [sitename]

[title]

[introtext]

[bodytext]

[unsubscribeall]

This is an autogenerated news mail, please do not respond";
$compilednewsmailHTML = "<table bgcolor=\"#EEEEEE\" width=\"100%\">
<tr>
<td>
<font size=\"-1\"><strong>[title]</strong>
<font color=\"#555555\"> (by [author], published [publishdatetime])</font><br>
<em>[introtext]</em><br>
[bodytext]</font>
</td>
</tr>
</table><br>";
$compilednewsmailText = "[title] (by [author], published [publishdatetime])
[introtext]
[bodytext]
_______________________________________________________________

";
$mailformat = "2";
$mailformatmessage = "Select Your prefered e-mail format";
$autoresend = "1";
$unsubscribealltext = "Click here to end all Your subscriptions";
$receiveremail = "";
?>