<?php

/**
* @version 2.7.2
* @package Joomla 1.5
* @subpackage DT Register
* @copyright Copyright (C) 2006 DTH Development
* @copyright contact dthdev@dthdevelopment.com
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
*/

class DtregisterModelCountry extends DtrModel 
{

	var $countries=array(
								'Algeria'=>'Algeria',
								'Andorra'=>'Andorra',
								'Angola'=>'Angola',
								'Antigua'=>'Antigua &amp; Barbuda',
								'Argentina'=>'Argentina',
								'Armenia'=>'Armenia',
								'Australia'=>'Australia',
								'Austria'=>'Austria',
								'Azerbaijan'=>'Azerbaijan',
								'Bahamas'=>'Bahamas',
								'Bahrain'=>'Bahrain',
								'Bangladesh'=>'Bangladesh',
								'Barbados'=>'Barbados',
								'Belarus'=>'Belarus',
								'Belgium'=>'Belgium',
								'Belize'=>'Belize',
								'Benin'=>'Benin',
								'Bhutan'=>'Bhutan',
								'Bolivia'=>'Bolivia',
								'Bosnia'=>'Bosnia &amp; Herzegovina',
								'Botswana'=>'Botswana',
								'Brazil'=>'Brazil',
								'Brunei'=>'Brunei Darussalam',
								'Bulgaria'=>'Bulgaria',
								'Burkina'=>'Burkina Faso',
								'Burma'=>'Burma (Myanmar)',
								'Burundi'=>'Burundi',
								'Cambodia'=>'Cambodia',
								'Cameroon'=>'Cameroon',
								'Canada'=>'Canada',
								'Verde'=>'Cape Verde',
								'Cayman'=>'Cayman Islands',
								'Central African Republic'=>'Central African Republic',
								'Chad'=>'Chad',
								'Brazil'=>'Brazil',					
		                        'Chile'=>'Chile',
		                        'China'=>'China',
								'Colombia'=>'Colombia',
								'Comoros'=>'Comoros',
								'Congo'=>'Congo',
								'Congo, Democratic Republic of the'=>'Congo, Democratic Republic of the',
								'Costa Rica'=>'Costa Rica',
								"C&ocirc;te d'Ivoir"=>"C&ocirc;te d'Ivoir",
								'Croatia'=>'Croatia',
								'Cuba'=>'Cuba',
								'Cyprus'=>'Cyprus',
								'Czech Republic'=>'Czech Republic',
								'Denmark'=>'Denmark',
								'Djibouti'=>'Djibouti',
								'Dominica'=>'Dominica',
								'Dominican Republic'=>'Dominican Republic',
								'Ecuador'=>'Ecuador',
								'East Timor'=>'East Timor',
								'Egypt'=>'Egypt',
								'El Salvador'=>'El Salvador',
								'England'=>'England',	
								'Equatorial Guinea'=>'Equatorial Guinea',
								'Eritrea'=>'Eritrea',
								'Estonia'=>'Estonia',
								'Ethiopia'=>'Ethiopia',
								'Fiji'=>'Fiji',
								'Finland'=>'Finland',
								'France'=>'France',
								'Gabon'=>'Gabon',
								'Gambia, Th'=>'Gambia, Th',
								'Georgia'=>'Georgia',
								'Germany'=>'Germany',
								'Ghana'=>'Ghana',
								'Great Britain'=>'Great Britain',
								'Greece'=>'Grenada',
								'Grenada'=>'Bahrain',
								'Guatemala'=>'Guatemala',
								'Guinea'=>'Guinea',
								'Guinea-Bissau'=>'Guinea-Bissau',
								'Guyana'=>'Guyana',
								'Haiti'=>'Haiti',
								'Honduras'=>'Honduras',
								'Hong Kong'=>'Hong Kong',
								'Hungary'=>'Hungary',
								'Iceland'=>'Iceland',
								'India'=>'India',
								'Indonesia'=>'Indonesia',
								'Iran'=>'Iran',
								'Iraq'=>'Iraq',
								'Ireland'=>'Ireland',
								'Israel'=>'Israel',
								'Italy'=>'Italy',
								'Jamaica'=>'Jamaica',
								'Japan'=>'Japan',
								'Jordan'=>'Jordan',
								'Kazakhstan'=>'Kazakhstan',
								'Kenya'=>'Kenya',
								'Kiribati'=>'Kiribati',
								'Korea, North'=>'Korea, North',
								'Korea, South'=>'Korea, South',
								'Kuwait'=>'Kuwait',					
		                        'Kyrgyzstan'=>'Kyrgyzstan',
								'Laos'=>'Laos',
								'Latvia'=>'Latvia',
								'Lebanon'=>'Lebanon',
								'Lesotho'=>'Lesotho',
								'Liberia'=>'Liberia',
								"Libya"=>"Libya",
								'Liechtenstein'=>'Liechtenstein',
								'Lithuania'=>'Lithuania',
								'Lithuania'=>'Lithuania',
								'Luxembourg'=>'Luxembourg',
								'Macedonia'=>'Macedonia',
								'Madagascar'=>'Madagascar',
				                'Malawi'=>'Malawi',
								'Malaysia'=>'Malaysia',
								'Maldives'=>'Maldives',
								'Mali'=>'Mali',
								'Malta'=>'Malta',
								'Marshall Islands'=>'Marshall Islands',
								'Mauritania'=>'Mauritania',
								'Mauritius'=>'Mauritius',
								'Mexico'=>'Mexico',
								'Micronesia'=>'Micronesia',
								'Moldova'=>'Moldova',
								'Monaco'=>'Monaco',
								'Mongolia'=>'Mongolia',
								'Montenegro'=>'Montenegro',
								'Morocco'=>'Morocco',
								'Mozambique'=>'Mozambique',
								'Mozambique'=>'Mozambique',
								'Myanmar'=>'Myanmar',
								'Namibia'=>'Namibia',
								'Nauru'=>'Nauru',
								'Nepal'=>'Nepal',
								'The Netherlands'=>'The Netherlands',
								'New Zealand'=>'New Zealand',
								'Nicaragua'=>'Nicaragua',
								'Niger'=>'Niger',
								'Nigeria'=>'Nigeria',
								'Norway'=>'Norway',
								'Oman'=>'Oman',
								'Pakistan'=>'Pakistan',
								'Palestinian State*'=>'Palestinian State*',
								'Panama'=>'Panama',
								'Papua New Guinea'=>'Papua New Guinea',
								'Paraguay'=>'Paraguay',
								'Peru'=>'Peru',
								'Philippines'=>'Philippines',
								'Poland'=>'Poland',
								'Portugal'=>'Portugal',
								'Qatar'=>'Qatar',
								'Romania'=>'Romania',
								'Russia'=>'Russia',
								'Rwanda'=>'Rwanda',
								'St. Kitts &amp; Nevis'=>'St. Kitts &amp; Nevis',
								'St. Lucia'=>'St. Lucia',
								'Samoa'=>'Samoa',					
		                        'San Marino'=>'San Marino',
								'S&atilde;o Tom&eacute; &amp; Pr&iacute;ncipe'=>'S&atilde;o Tom&eacute; &amp; Pr&iacute;ncipe',
								'Saudi Arabia'=>'Saudi Arabia',
								'Senegal'=>'Senegal',
								'Serbia'=>'Serbia',
								'Sierra Leone'=>'Sierra Leone',
								'Singapore'=>'Singapore',
								'Slovakia'=>'Slovakia',
								'Slovenia'=>'Slovenia',
								'Solomon Islands'=>'Solomon Islands',
								'Somalia'=>'Somalia',
								'South Africa'=>'South Africa',
								'Spain'=>'Spain',
								'Sri Lanka'=>'Sri Lanka',
								'Sudan'=>'Sudan',
								'Suriname'=>'Suriname',
								'Swaziland'=>'Swaziland',
								'Sweden'=>'Sweden',
								'Switzerland'=>'Switzerland',
								'Syria'=>'Syria',
								'Taiwan'=>'Taiwan',
								'Tajikistan'=>'Tajikistan',
								'Tanzania'=>'Tanzania',
								'Thailand'=>'Thailand',
								'Togo'=>'Togo',
								'Tonga'=>'Tonga',
								'Trinidad &amp; Tobago'=>'Trinidad &amp; Tobago',
							    'Tunisia'=>'Tunisia',
								'Turkey'=>'Turkey',
								'Turkmenistan'=>'Turkmenistan',
								'Tuvalu'=>'Tuvalu',
								'Uganda'=>'Uganda',
								'Ukraine'=>'Ukraine',
								'United Arab Emirates'=>'United Arab Emirates',
								'United Kingdom'=>'United Kingdom',
								'United States'=>'United States',
								'Uruguay'=>'Uruguay',
								'Uzbekistan'=>'Uzbekistan',
								'Vanuatu'=>'Vanuatu',
								'Vatican City (Holy See)'=>'Vatican City (Holy See)',
								'Venezuela'=>'Venezuela',					
		                        'Vietnam'=>'Vietnam',
								'Western Sahara*'=>'Western Sahara*',
								'Yemen'=>'Yemen',
								'Yugoslavia'=>'Yugoslavia',
								'Zaire'=>'Zaire',
								'Zambia'=>'Zambia',
								'Zimbabwe'=>'Zimbabwe'
									
							);

  function getCountry(){
	  
	 return $this->countries;
     
  }

}

?>